server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.135.199:8848
        group: akiCloud
    gateway:
      routes:
        - id: systemService
          uri: lb://systemService #loadBalance
          predicates:
            - Path=/systemService/**